import {Country} from '../types';

export const nigerianStates = [
	'Abia',
	'Adamawa',
	'Akwa Ibom',
	'Anambra',
	'Bauchi',
	'Bayelsa',
	'Benue',
	'Borno',
	'Cross River',
	'Delta',
	'Ebonyi',
	'Edo',
	'Ekiti',
	'Enugu',
	'Federal Capital Territory',
	'Gombe',
	'Imo',
	'Jigawa',
	'Kaduna',
	'Kano',
	'Katsina',
	'Kebbi',
	'Kogi',
	'Kwara',
	'Lagos',
	'Nasarawa',
	'Niger',
	'Ogun',
	'Ondo',
	'Osun',
	'Oyo',
	'Plateau',
	'Rivers',
	'Sokoto',
	'Taraba',
	'Yobe',
	'Zamfara'
];


export const platformCountries: Country[] = [
	{name: 'Afghanistan', dialCode: '+93', flagEmoji: '🇦🇫', code: 'AF'},
	{name: 'Albania', dialCode: '+355', flagEmoji: '🇦🇱', code: 'AL'},
	{name: 'Algeria', dialCode: '+213', flagEmoji: '🇩🇿', code: 'DZ'},
	{name: 'Andorra', dialCode: '+376', flagEmoji: '🇦🇩', code: 'AD'},
	{name: 'Angola', dialCode: '+244', flagEmoji: '🇦🇴', code: 'AO'},
	{
		name: 'Antigua and Barbuda',
		dialCode: '+1-268',
		flagEmoji: '🇦🇬',
		code: 'AG',
	},
	{name: 'Argentina', dialCode: '+54', flagEmoji: '🇦🇷', code: 'AR'},
	{name: 'Armenia', dialCode: '+374', flagEmoji: '🇦🇲', code: 'AM'},
	{name: 'Australia', dialCode: '+61', flagEmoji: '🇦🇺', code: 'AU'},
	{name: 'Austria', dialCode: '+43', flagEmoji: '🇦🇹', code: 'AT'},
	{name: 'Azerbaijan', dialCode: '+994', flagEmoji: '🇦🇿', code: 'AZ'},
	{name: 'Bahamas', dialCode: '+1-242', flagEmoji: '🇧🇸', code: 'BS'},
	{name: 'Bahrain', dialCode: '+973', flagEmoji: '🇧🇭', code: 'BH'},
	{name: 'Bangladesh', dialCode: '+880', flagEmoji: '🇧🇩', code: 'BD'},
	{name: 'Barbados', dialCode: '+1-246', flagEmoji: '🇧🇧', code: 'BB'},
	{name: 'Belarus', dialCode: '+375', flagEmoji: '🇧🇾', code: 'BY'},
	{name: 'Belgium', dialCode: '+32', flagEmoji: '🇧🇪', code: 'BE'},
	{name: 'Belize', dialCode: '+501', flagEmoji: '🇧🇿', code: 'BZ'},
	{name: 'Benin', dialCode: '+229', flagEmoji: '🇧🇯', code: 'BJ'},
	{name: 'Bhutan', dialCode: '+975', flagEmoji: '🇧🇹', code: 'BT'},
	{name: 'Bolivia', dialCode: '+591', flagEmoji: '🇧🇴', code: 'BO'},
	{
		name: 'Bosnia and Herzegovina',
		dialCode: '+387',
		flagEmoji: '🇧🇦',
		code: 'BA',
	},
	{name: 'Botswana', dialCode: '+267', flagEmoji: '🇧🇼', code: 'BW'},
	{name: 'Brazil', dialCode: '+55', flagEmoji: '🇧🇷', code: 'BR'},
	{name: 'Brunei', dialCode: '+673', flagEmoji: '🇧🇳', code: 'BN'},
	{name: 'Bulgaria', dialCode: '+359', flagEmoji: '🇧🇬', code: 'BG'},
	{name: 'Burkina Faso', dialCode: '+226', flagEmoji: '🇧🇫', code: 'BF'},
	{name: 'Burundi', dialCode: '+257', flagEmoji: '🇧🇮', code: 'BI'},
	{name: 'Cabo Verde', dialCode: '+238', flagEmoji: '🇨🇻', code: 'CV'},
	{name: 'Cambodia', dialCode: '+855', flagEmoji: '🇰🇭', code: 'KH'},
	{name: 'Cameroon', dialCode: '+237', flagEmoji: '🇨🇲', code: 'CM'},
	{name: 'Canada', dialCode: '+1', flagEmoji: '🇨🇦', code: 'CA'},
	{
		name: 'Central African Republic',
		dialCode: '+236',
		flagEmoji: '🇨🇫',
		code: 'CF',
	},
	{name: 'Chad', dialCode: '+235', flagEmoji: '🇹🇩', code: 'TD'},
	{name: 'Chile', dialCode: '+56', flagEmoji: '🇨🇱', code: 'CL'},
	{name: 'China', dialCode: '+86', flagEmoji: '🇨🇳', code: 'CN'},
	{name: 'Colombia', dialCode: '+57', flagEmoji: '🇨🇴', code: 'CO'},
	{name: 'Comoros', dialCode: '+269', flagEmoji: '🇰🇲', code: 'KM'},
	{
		name: 'Congo (Congo-Brazzaville)',
		dialCode: '+242',
		flagEmoji: '🇨🇬',
		code: 'CG',
	},
	{
		name: 'Congo (Congo-Kinshasa)',
		dialCode: '+243',
		flagEmoji: '🇨🇩',
		code: 'CD',
	},
	{name: 'Costa Rica', dialCode: '+506', flagEmoji: '🇨🇷', code: 'CR'},
	{name: 'Croatia', dialCode: '+385', flagEmoji: '🇭🇷', code: 'HR'},
	{name: 'Cuba', dialCode: '+53', flagEmoji: '🇨🇺', code: 'CU'},
	{name: 'Cyprus', dialCode: '+357', flagEmoji: '🇨🇾', code: 'CY'},
	{name: 'Czechia', dialCode: '+420', flagEmoji: '🇨🇿', code: 'CZ'},
	{name: 'Denmark', dialCode: '+45', flagEmoji: '🇩🇰', code: 'DK'},
	{name: 'Djibouti', dialCode: '+253', flagEmoji: '🇩🇯', code: 'DJ'},
	{name: 'Dominica', dialCode: '+1-767', flagEmoji: '🇩🇲', code: 'DM'},
	{
		name: 'Dominican Republic',
		dialCode: '+1-809',
		flagEmoji: '🇩🇴',
		code: 'DO',
	},
	{name: 'Ecuador', dialCode: '+593', flagEmoji: '🇪🇨', code: 'EC'},
	{name: 'Egypt', dialCode: '+20', flagEmoji: '🇪🇬', code: 'EG'},
	{name: 'El Salvador', dialCode: '+503', flagEmoji: '🇸🇻', code: 'SV'},
	{name: 'Equatorial Guinea', dialCode: '+240', flagEmoji: '🇬🇶', code: 'GQ'},
	{name: 'Eritrea', dialCode: '+291', flagEmoji: '🇪🇷', code: 'ER'},
	{name: 'Estonia', dialCode: '+372', flagEmoji: '🇪🇪', code: 'EE'},
	{name: 'Eswatini', dialCode: '+268', flagEmoji: '🇸🇿', code: 'SZ'},
	{name: 'Ethiopia', dialCode: '+251', flagEmoji: '🇪🇹', code: 'ET'},
	{name: 'Fiji', dialCode: '+679', flagEmoji: '🇫🇯', code: 'FJ'},
	{name: 'Finland', dialCode: '+358', flagEmoji: '🇫🇮', code: 'FI'},
	{name: 'France', dialCode: '+33', flagEmoji: '🇫🇷', code: 'FR'},
	{name: 'Gabon', dialCode: '+241', flagEmoji: '🇬🇦', code: 'GA'},
	{name: 'Gambia', dialCode: '+220', flagEmoji: '🇬🇲', code: 'GM'},
	{name: 'Georgia', dialCode: '+995', flagEmoji: '🇬🇪', code: 'GE'},
	{name: 'Germany', dialCode: '+49', flagEmoji: '🇩🇪', code: 'DE'},
	{name: 'Ghana', dialCode: '+233', flagEmoji: '🇬🇭', code: 'GH'},
	{name: 'Greece', dialCode: '+30', flagEmoji: '🇬🇷', code: 'GR'},
	{name: 'Grenada', dialCode: '+1-473', flagEmoji: '🇬🇩', code: 'GD'},
	{name: 'Guatemala', dialCode: '+502', flagEmoji: '🇬🇹', code: 'GT'},
	{name: 'Guinea', dialCode: '+224', flagEmoji: '🇬🇳', code: 'GN'},
	{name: 'Guinea-Bissau', dialCode: '+245', flagEmoji: '🇬🇼', code: 'GW'},
	{name: 'Guyana', dialCode: '+592', flagEmoji: '🇬🇾', code: 'GY'},
	{name: 'Haiti', dialCode: '+509', flagEmoji: '🇭🇹', code: 'HT'},
	{name: 'Honduras', dialCode: '+504', flagEmoji: '🇭🇳', code: 'HN'},
	{name: 'Hungary', dialCode: '+36', flagEmoji: '🇭🇺', code: 'HU'},
	{name: 'Iceland', dialCode: '+354', flagEmoji: '🇮🇸', code: 'IS'},
	{name: 'India', dialCode: '+91', flagEmoji: '🇮🇳', code: 'IN'},
	{name: 'Indonesia', dialCode: '+62', flagEmoji: '🇮🇩', code: 'ID'},
	{name: 'Iran', dialCode: '+98', flagEmoji: '🇮🇷', code: 'IR'},
	{name: 'Iraq', dialCode: '+964', flagEmoji: '🇮🇶', code: 'IQ'},
	{name: 'Ireland', dialCode: '+353', flagEmoji: '🇮🇪', code: 'IE'},
	{name: 'Israel', dialCode: '+972', flagEmoji: '🇮🇱', code: 'IL'},
	{name: 'Italy', dialCode: '+39', flagEmoji: '🇮🇹', code: 'IT'},
	{name: 'Jamaica', dialCode: '+1-876', flagEmoji: '🇯🇲', code: 'JM'},
	{name: 'Japan', dialCode: '+81', flagEmoji: '🇯🇵', code: 'JP'},
	{name: 'Jordan', dialCode: '+962', flagEmoji: '🇯🇴', code: 'JO'},
	{name: 'Kazakhstan', dialCode: '+7', flagEmoji: '🇰🇿', code: 'KZ'},
	{name: 'Kenya', dialCode: '+254', flagEmoji: '🇰🇪', code: 'KE'},
	{name: 'Kiribati', dialCode: '+686', flagEmoji: '🇰🇮', code: 'KI'},
	{name: 'Kuwait', dialCode: '+965', flagEmoji: '🇰🇼', code: 'KW'},
	{name: 'Kyrgyzstan', dialCode: '+996', flagEmoji: '🇰🇬', code: 'KG'},
	{name: 'Laos', dialCode: '+856', flagEmoji: '🇱🇦', code: 'LA'},
	{name: 'Latvia', dialCode: '+371', flagEmoji: '🇱🇻', code: 'LV'},
	{name: 'Lebanon', dialCode: '+961', flagEmoji: '🇱🇧', code: 'LB'},
	{name: 'Lesotho', dialCode: '+266', flagEmoji: '🇱🇸', code: 'LS'},
	{name: 'Liberia', dialCode: '+231', flagEmoji: '🇱🇷', code: 'LR'},
	{name: 'Libya', dialCode: '+218', flagEmoji: '🇱🇾', code: 'LY'},
	{name: 'Liechtenstein', dialCode: '+423', flagEmoji: '🇱🇮', code: 'LI'},
	{name: 'Lithuania', dialCode: '+370', flagEmoji: '🇱🇹', code: 'LT'},
	{name: 'Luxembourg', dialCode: '+352', flagEmoji: '🇱🇺', code: 'LU'},
	{name: 'Madagascar', dialCode: '+261', flagEmoji: '🇲🇬', code: 'MG'},
	{name: 'Malawi', dialCode: '+265', flagEmoji: '🇲🇼', code: 'MW'},
	{name: 'Malaysia', dialCode: '+60', flagEmoji: '🇲🇾', code: 'MY'},
	{name: 'Maldives', dialCode: '+960', flagEmoji: '🇲🇻', code: 'MV'},
	{name: 'Mali', dialCode: '+223', flagEmoji: '🇲🇱', code: 'ML'},
	{name: 'Malta', dialCode: '+356', flagEmoji: '🇲🇹', code: 'MT'},
	{name: 'Marshall Islands', dialCode: '+692', flagEmoji: '🇲🇭', code: 'MH'},
	{name: 'Mauritania', dialCode: '+222', flagEmoji: '🇲🇷', code: 'MR'},
	{name: 'Mauritius', dialCode: '+230', flagEmoji: '🇲🇺', code: 'MU'},
	{name: 'Mexico', dialCode: '+52', flagEmoji: '🇲🇽', code: 'MX'},
	{name: 'Micronesia', dialCode: '+691', flagEmoji: '🇫🇲', code: 'FM'},
	{name: 'Moldova', dialCode: '+373', flagEmoji: '🇲🇩', code: 'MD'},
	{name: 'Monaco', dialCode: '+377', flagEmoji: '🇲🇨', code: 'MC'},
	{name: 'Mongolia', dialCode: '+976', flagEmoji: '🇲🇳', code: 'MN'},
	{name: 'Montenegro', dialCode: '+382', flagEmoji: '🇲🇪', code: 'ME'},
	{name: 'Morocco', dialCode: '+212', flagEmoji: '🇲🇦', code: 'MA'},
	{name: 'Mozambique', dialCode: '+258', flagEmoji: '🇲🇿', code: 'MZ'},
	{name: 'Myanmar', dialCode: '+95', flagEmoji: '🇲🇲', code: 'MM'},
	{name: 'Namibia', dialCode: '+264', flagEmoji: '🇳🇦', code: 'NA'},
	{name: 'Nauru', dialCode: '+674', flagEmoji: '🇳🇷', code: 'NR'},
	{name: 'Nepal', dialCode: '+977', flagEmoji: '🇳🇵', code: 'NP'},
	{name: 'Netherlands', dialCode: '+31', flagEmoji: '🇳🇱', code: 'NL'},
	{name: 'New Zealand', dialCode: '+64', flagEmoji: '🇳🇿', code: 'NZ'},
	{name: 'Nicaragua', dialCode: '+505', flagEmoji: '🇳🇮', code: 'NI'},
	{name: 'Niger', dialCode: '+227', flagEmoji: '🇳🇪', code: 'NE'},
	{name: 'Nigeria', dialCode: '+234', flagEmoji: '🇳🇬', code: 'NG'},
	{name: 'North Korea', dialCode: '+850', flagEmoji: '🇰🇵', code: 'KP'},
	{name: 'North Macedonia', dialCode: '+389', flagEmoji: '🇲🇰', code: 'MK'},
	{name: 'Norway', dialCode: '+47', flagEmoji: '🇳🇴', code: 'NO'},
	{name: 'Oman', dialCode: '+968', flagEmoji: '🇴🇲', code: 'OM'},
	{name: 'Pakistan', dialCode: '+92', flagEmoji: '🇵🇰', code: 'PK'},
	{name: 'Palau', dialCode: '+680', flagEmoji: '🇵🇼', code: 'PW'},
	{name: 'Palestine', dialCode: '+970', flagEmoji: '🇵🇸', code: 'PS'},
	{name: 'Panama', dialCode: '+507', flagEmoji: '🇵🇦', code: 'PA'},
	{name: 'Papua New Guinea', dialCode: '+675', flagEmoji: '🇵🇬', code: 'PG'},
	{name: 'Paraguay', dialCode: '+595', flagEmoji: '🇵🇾', code: 'PY'},
	{name: 'Peru', dialCode: '+51', flagEmoji: '🇵🇪', code: 'PE'},
	{name: 'Philippines', dialCode: '+63', flagEmoji: '🇵🇭', code: 'PH'},
	{name: 'Poland', dialCode: '+48', flagEmoji: '🇵🇱', code: 'PL'},
	{name: 'Portugal', dialCode: '+351', flagEmoji: '🇵🇹', code: 'PT'},
	{name: 'Qatar', dialCode: '+974', flagEmoji: '🇶🇦', code: 'QA'},
	{name: 'Romania', dialCode: '+40', flagEmoji: '🇷🇴', code: 'RO'},
	{name: 'Russia', dialCode: '+7', flagEmoji: '🇷🇺', code: 'RU'},
	{name: 'Rwanda', dialCode: '+250', flagEmoji: '🇷🇼', code: 'RW'},
	{
		name: 'Saint Kitts and Nevis',
		dialCode: '+1-869',
		flagEmoji: '🇰🇳',
		code: 'KN',
	},
	{name: 'Saint Lucia', dialCode: '+1-758', flagEmoji: '🇱🇨', code: 'LC'},
	{
		name: 'Saint Vincent and the Grenadines',
		dialCode: '+1-784',
		flagEmoji: '🇻🇨',
		code: 'VC',
	},
	{name: 'Samoa', dialCode: '+685', flagEmoji: '🇼🇸', code: 'WS'},
	{name: 'San Marino', dialCode: '+378', flagEmoji: '🇸🇲', code: 'SM'},
	{
		name: 'Sao Tome and Principe',
		dialCode: '+239',
		flagEmoji: '🇸🇹',
		code: 'ST',
	},
	{name: 'Saudi Arabia', dialCode: '+966', flagEmoji: '🇸🇦', code: 'SA'},
	{name: 'Senegal', dialCode: '+221', flagEmoji: '🇸🇳', code: 'SN'},
	{name: 'Serbia', dialCode: '+381', flagEmoji: '🇷🇸', code: 'RS'},
	{name: 'Seychelles', dialCode: '+248', flagEmoji: '🇸🇨', code: 'SC'},
	{name: 'Sierra Leone', dialCode: '+232', flagEmoji: '🇸🇱', code: 'SL'},
	{name: 'Singapore', dialCode: '+65', flagEmoji: '🇸🇬', code: 'SG'},
	{name: 'Slovakia', dialCode: '+421', flagEmoji: '🇸🇰', code: 'SK'},
	{name: 'Slovenia', dialCode: '+386', flagEmoji: '🇸🇮', code: 'SI'},
	{name: 'Solomon Islands', dialCode: '+677', flagEmoji: '🇸🇧', code: 'SB'},
	{name: 'Somalia', dialCode: '+252', flagEmoji: '🇸🇴', code: 'SO'},
	{name: 'South Africa', dialCode: '+27', flagEmoji: '🇿🇦', code: 'ZA'},
	{name: 'South Korea', dialCode: '+82', flagEmoji: '🇰🇷', code: 'KR'},
	{name: 'South Sudan', dialCode: '+211', flagEmoji: '🇸🇸', code: 'SS'},
	{name: 'Spain', dialCode: '+34', flagEmoji: '🇪🇸', code: 'ES'},
	{name: 'Sri Lanka', dialCode: '+94', flagEmoji: '🇱🇰', code: 'LK'},
	{name: 'Sudan', dialCode: '+249', flagEmoji: '🇸🇩', code: 'SD'},
	{name: 'Suriname', dialCode: '+597', flagEmoji: '🇸🇷', code: 'SR'},
	{name: 'Sweden', dialCode: '+46', flagEmoji: '🇸🇪', code: 'SE'},
	{name: 'Switzerland', dialCode: '+41', flagEmoji: '🇨🇭', code: 'CH'},
	{name: 'Syria', dialCode: '+963', flagEmoji: '🇸🇾', code: 'SY'},
	{name: 'Taiwan', dialCode: '+886', flagEmoji: '🇹🇼', code: 'TW'},
	{name: 'Tajikistan', dialCode: '+992', flagEmoji: '🇹🇯', code: 'TJ'},
	{name: 'Tanzania', dialCode: '+255', flagEmoji: '🇹🇿', code: 'TZ'},
	{name: 'Thailand', dialCode: '+66', flagEmoji: '🇹🇭', code: 'TH'},
	{name: 'Togo', dialCode: '+228', flagEmoji: '🇹🇬', code: 'TG'},
	{name: 'Tonga', dialCode: '+676', flagEmoji: '🇹🇴', code: 'TO'},
	{
		name: 'Trinidad and Tobago',
		dialCode: '+1-868',
		flagEmoji: '🇹🇹',
		code: 'TT',
	},
	{name: 'Tunisia', dialCode: '+216', flagEmoji: '🇹🇳', code: 'TN'},
	{name: 'Turkey', dialCode: '+90', flagEmoji: '🇹🇷', code: 'TR'},
	{name: 'Turkmenistan', dialCode: '+993', flagEmoji: '🇹🇲', code: 'TM'},
	{name: 'Tuvalu', dialCode: '+688', flagEmoji: '🇹🇻', code: 'TV'},
	{name: 'Uganda', dialCode: '+256', flagEmoji: '🇺🇬', code: 'UG'},
	{name: 'Ukraine', dialCode: '+380', flagEmoji: '🇺🇦', code: 'UA'},
	{
		name: 'United Arab Emirates',
		dialCode: '+971',
		flagEmoji: '🇦🇪',
		code: 'AE',
	},
	{name: 'United Kingdom', dialCode: '+44', flagEmoji: '🇬🇧', code: 'GB'},
	{name: 'United States', dialCode: '+1', flagEmoji: '🇺🇸', code: 'US'},
	{name: 'Uruguay', dialCode: '+598', flagEmoji: '🇺🇾', code: 'UY'},
	{name: 'Uzbekistan', dialCode: '+998', flagEmoji: '🇺🇿', code: 'UZ'},
	{name: 'Vanuatu', dialCode: '+678', flagEmoji: '🇻🇺', code: 'VU'},
	{name: 'Vatican City', dialCode: '+379', flagEmoji: '🇻🇦', code: 'VA'},
	{name: 'Venezuela', dialCode: '+58', flagEmoji: '🇻🇪', code: 'VE'},
	{name: 'Vietnam', dialCode: '+84', flagEmoji: '🇻🇳', code: 'VN'},
	{name: 'Yemen', dialCode: '+967', flagEmoji: '🇾🇪', code: 'YE'},
	{name: 'Zambia', dialCode: '+260', flagEmoji: '🇿🇲', code: 'ZM'},
	{name: 'Zimbabwe', dialCode: '+263', flagEmoji: '🇿🇼', code: 'ZW'},
];
